const WEATHER_REQUEST_SEND = "WEATHER_REQUEST_SEND";
const WEATHER_REQUEST_SUCCESS = "WEATHER_REQUEST_SUCCESS";
const WEATHER_REQUEST_FAILURE = "WEATHER_REQUEST_FAILURE";

export { WEATHER_REQUEST_SEND, WEATHER_REQUEST_SUCCESS, WEATHER_REQUEST_FAILURE };